/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AEmptyinstrInstr extends PInstr
{
    private PEmptyinstr _emptyinstr_;

    public AEmptyinstrInstr()
    {
        // Constructor
    }

    public AEmptyinstrInstr(
        @SuppressWarnings("hiding") PEmptyinstr _emptyinstr_)
    {
        // Constructor
        setEmptyinstr(_emptyinstr_);

    }

    @Override
    public Object clone()
    {
        return new AEmptyinstrInstr(
            cloneNode(this._emptyinstr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEmptyinstrInstr(this);
    }

    public PEmptyinstr getEmptyinstr()
    {
        return this._emptyinstr_;
    }

    public void setEmptyinstr(PEmptyinstr node)
    {
        if(this._emptyinstr_ != null)
        {
            this._emptyinstr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._emptyinstr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._emptyinstr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._emptyinstr_ == child)
        {
            this._emptyinstr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._emptyinstr_ == oldChild)
        {
            setEmptyinstr((PEmptyinstr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
