/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AFoncdeclistProgram extends PProgram
{
    private PFoncdeclist _foncdeclist_;

    public AFoncdeclistProgram()
    {
        // Constructor
    }

    public AFoncdeclistProgram(
        @SuppressWarnings("hiding") PFoncdeclist _foncdeclist_)
    {
        // Constructor
        setFoncdeclist(_foncdeclist_);

    }

    @Override
    public Object clone()
    {
        return new AFoncdeclistProgram(
            cloneNode(this._foncdeclist_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFoncdeclistProgram(this);
    }

    public PFoncdeclist getFoncdeclist()
    {
        return this._foncdeclist_;
    }

    public void setFoncdeclist(PFoncdeclist node)
    {
        if(this._foncdeclist_ != null)
        {
            this._foncdeclist_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._foncdeclist_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._foncdeclist_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._foncdeclist_ == child)
        {
            this._foncdeclist_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._foncdeclist_ == oldChild)
        {
            setFoncdeclist((PFoncdeclist) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
