/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AIfinstrInstr extends PInstr
{
    private PIfinstr _ifinstr_;

    public AIfinstrInstr()
    {
        // Constructor
    }

    public AIfinstrInstr(
        @SuppressWarnings("hiding") PIfinstr _ifinstr_)
    {
        // Constructor
        setIfinstr(_ifinstr_);

    }

    @Override
    public Object clone()
    {
        return new AIfinstrInstr(
            cloneNode(this._ifinstr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIfinstrInstr(this);
    }

    public PIfinstr getIfinstr()
    {
        return this._ifinstr_;
    }

    public void setIfinstr(PIfinstr node)
    {
        if(this._ifinstr_ != null)
        {
            this._ifinstr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ifinstr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._ifinstr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._ifinstr_ == child)
        {
            this._ifinstr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._ifinstr_ == oldChild)
        {
            setIfinstr((PIfinstr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
