/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AInstrInstrblocbis extends PInstrblocbis
{
    private PInstr _instr_;
    private PInstrblocbis _instrblocbis_;

    public AInstrInstrblocbis()
    {
        // Constructor
    }

    public AInstrInstrblocbis(
        @SuppressWarnings("hiding") PInstr _instr_,
        @SuppressWarnings("hiding") PInstrblocbis _instrblocbis_)
    {
        // Constructor
        setInstr(_instr_);

        setInstrblocbis(_instrblocbis_);

    }

    @Override
    public Object clone()
    {
        return new AInstrInstrblocbis(
            cloneNode(this._instr_),
            cloneNode(this._instrblocbis_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAInstrInstrblocbis(this);
    }

    public PInstr getInstr()
    {
        return this._instr_;
    }

    public void setInstr(PInstr node)
    {
        if(this._instr_ != null)
        {
            this._instr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._instr_ = node;
    }

    public PInstrblocbis getInstrblocbis()
    {
        return this._instrblocbis_;
    }

    public void setInstrblocbis(PInstrblocbis node)
    {
        if(this._instrblocbis_ != null)
        {
            this._instrblocbis_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._instrblocbis_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._instr_)
            + toString(this._instrblocbis_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._instr_ == child)
        {
            this._instr_ = null;
            return;
        }

        if(this._instrblocbis_ == child)
        {
            this._instrblocbis_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._instr_ == oldChild)
        {
            setInstr((PInstr) newChild);
            return;
        }

        if(this._instrblocbis_ == oldChild)
        {
            setInstrblocbis((PInstrblocbis) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
