/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class ALastVardeclistbis extends PVardeclistbis
{
    private TComma _comma_;
    private PVardec _vardec_;

    public ALastVardeclistbis()
    {
        // Constructor
    }

    public ALastVardeclistbis(
        @SuppressWarnings("hiding") TComma _comma_,
        @SuppressWarnings("hiding") PVardec _vardec_)
    {
        // Constructor
        setComma(_comma_);

        setVardec(_vardec_);

    }

    @Override
    public Object clone()
    {
        return new ALastVardeclistbis(
            cloneNode(this._comma_),
            cloneNode(this._vardec_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALastVardeclistbis(this);
    }

    public TComma getComma()
    {
        return this._comma_;
    }

    public void setComma(TComma node)
    {
        if(this._comma_ != null)
        {
            this._comma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comma_ = node;
    }

    public PVardec getVardec()
    {
        return this._vardec_;
    }

    public void setVardec(PVardec node)
    {
        if(this._vardec_ != null)
        {
            this._vardec_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._vardec_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._comma_)
            + toString(this._vardec_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._comma_ == child)
        {
            this._comma_ = null;
            return;
        }

        if(this._vardec_ == child)
        {
            this._vardec_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._comma_ == oldChild)
        {
            setComma((TComma) newChild);
            return;
        }

        if(this._vardec_ == oldChild)
        {
            setVardec((PVardec) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
