/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AOneVardeclist extends PVardeclist
{
    private PVardec _vardec_;

    public AOneVardeclist()
    {
        // Constructor
    }

    public AOneVardeclist(
        @SuppressWarnings("hiding") PVardec _vardec_)
    {
        // Constructor
        setVardec(_vardec_);

    }

    @Override
    public Object clone()
    {
        return new AOneVardeclist(
            cloneNode(this._vardec_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOneVardeclist(this);
    }

    public PVardec getVardec()
    {
        return this._vardec_;
    }

    public void setVardec(PVardec node)
    {
        if(this._vardec_ != null)
        {
            this._vardec_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._vardec_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._vardec_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._vardec_ == child)
        {
            this._vardec_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._vardec_ == oldChild)
        {
            setVardec((PVardec) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
