/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AWhileinstrInstr extends PInstr
{
    private PWhileinstr _whileinstr_;

    public AWhileinstrInstr()
    {
        // Constructor
    }

    public AWhileinstrInstr(
        @SuppressWarnings("hiding") PWhileinstr _whileinstr_)
    {
        // Constructor
        setWhileinstr(_whileinstr_);

    }

    @Override
    public Object clone()
    {
        return new AWhileinstrInstr(
            cloneNode(this._whileinstr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAWhileinstrInstr(this);
    }

    public PWhileinstr getWhileinstr()
    {
        return this._whileinstr_;
    }

    public void setWhileinstr(PWhileinstr node)
    {
        if(this._whileinstr_ != null)
        {
            this._whileinstr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._whileinstr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._whileinstr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._whileinstr_ == child)
        {
            this._whileinstr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._whileinstr_ == oldChild)
        {
            setWhileinstr((PWhileinstr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
