/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AWriteinstrInstr extends PInstr
{
    private PWriteinstr _writeinstr_;

    public AWriteinstrInstr()
    {
        // Constructor
    }

    public AWriteinstrInstr(
        @SuppressWarnings("hiding") PWriteinstr _writeinstr_)
    {
        // Constructor
        setWriteinstr(_writeinstr_);

    }

    @Override
    public Object clone()
    {
        return new AWriteinstrInstr(
            cloneNode(this._writeinstr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAWriteinstrInstr(this);
    }

    public PWriteinstr getWriteinstr()
    {
        return this._writeinstr_;
    }

    public void setWriteinstr(PWriteinstr node)
    {
        if(this._writeinstr_ != null)
        {
            this._writeinstr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._writeinstr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._writeinstr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._writeinstr_ == child)
        {
            this._writeinstr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._writeinstr_ == oldChild)
        {
            setWriteinstr((PWriteinstr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
